Remove faraday_middleware gem
Beyond-Finance/reporting_client pull request #12
Opened 2023-02-28 22:19 UTC by SteveSchneider

* gem is deprecated, does not support faraday 2.0

* increment reporting_client version

2023-02-28 22:38 UTC, SteveSchneider commented
faraday_middleware is deprecated for faraday >= 2.0
https://github.com/lostisland/faraday_middleware#%EF%B8%8F-deprecation-warning-%EF%B8%8F
https://github.com/lostisland/faraday/blob/main/UPGRADING.md

Relevant info:

**That's great! What should I change in my code immediately after upgrading?**

- If you just use the default net_http adapter, then you don't need to do anything!

- We've promoted the highly popular JSON middleware (both request encoding and response parsing) to a core middleware and it will now be shipped together with Faraday. We expect many faraday_middleware users will be able to just stop using the extra dependency thanks to this.

2023-02-28 22:49 UTC, jacobdaddario commented
Hey Steve! Thanks for noticing this, it's great to clean out an unused dependency. I recently looked through the repo, and it seemed to me like we weren't using the gem, so I think we're good to go on that front.

Did you see anything in the repo that you think we should be worried about? I'm just concerned about accidentally breaking something in the gem by removing this. Just want to cover bases before removing the dependency.

2023-02-28 23:16 UTC, SteveSchneider commented
> Hey Steve! Thanks for noticing this, it's great to clean out an unused dependency. I recently looked through the repo, and it seemed to me like we weren't using the gem, so I think we're good to go on that front.
> 
> Did you see anything in the repo that you think we should be worried about? I'm just concerned about accidentally breaking something in the gem by removing this. Just want to cover bases before removing the dependency.

Hey @jacobdaddario, I didn't notice anything that I thought would break in the gem itself. There could be breaking changes in apps consuming the gem, such as for example trying to use `FaradayMiddleware::FollowRedirects` when that namespace no longer exists and it would be moved to `Faraday::FollowRedirects::Middleware` (which is included from a separate gem).

2023-03-01 04:20 UTC, spacechurro requested changes

2023-03-01 04:20 UTC, spacechurro commented on reporting_client.gemspec
> +  spec.add_runtime_dependency 'faraday', '~> 2.0'
Im thinking instead of pegging it to the 2.x release we should make it just a minimum. Can we change the `~>` to a `>=`?

2023-03-01 15:48 UTC, spacechurro approved these changes

2023-03-01 15:49 UTC, merged